Improve etcd client calls

diff --git a/k8s/danm/charts/enb/templates/deployment.yaml b/k8s/danm/charts/enb/templates/deployment.yaml
--- a/k8s/danm/charts/enb/templates/deployment.yaml
+++ b/k8s/danm/charts/enb/templates/deployment.yaml
@@ -86,21 +86,29 @@ metadata:
   name: enb-init-script
 data:
   init.sh: |2
-    if [ $(curl http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip -s -o /dev/null -w "%{http_code}") == "200" ]; then
+    http_code=$(curl http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip -s -o /dev/null -w "%{http_code}")
+    if [ "$http_code" == "200" ]; then
         mme_s1c_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip | jq  -r ".node.value")
-    else
+    elif [ "$http_code" == "404" ]; then
         mme_s1c_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip?wait=true | jq  -r ".node.value")
+    else
+        echo "ERROR - eNB pod cannot reach the etcd service"
+        traceroute $LTE_ETCD_SERVICE_HOST -m 5 -p 12379 -q 1
+        exit 1
     fi
     sed -i "s|mme_addr:.*|mme_addr: \"${mme_s1c_ip}:36412\"|g" /etc/gw-tester/enb.yml
 
-    euu_nic=$(ip a | grep {{ .Values.euu.container_prefix | quote }} | awk -v FS="(: |@)" '{print $2; exit}')
-    euu_ip=$(ifconfig $euu_nic | awk '/inet addr/{print substr($2,6)}')
     s1c_ip=$(ifconfig $(ip a | grep {{ .Values.s1c.container_prefix | quote }} | awk -v FS="(: |@)" '{print $2; exit}') | awk '/inet addr/{print substr($2,6)}')
-    sed -i "s|s1c_ip:.*|s1c_ip: \"${s1c_ip}\"|g" /etc/gw-tester/enb.yml
-    s1u_ip=$(ifconfig $(ip a | grep {{ .Values.s1u.container_prefix | quote }} | awk -v FS="(: |@)" '{print $2; exit}') | awk '/inet addr/{print substr($2,6)}')
-    sed -i "s|s1u_ip:.*|s1u_ip: \"${s1u_ip}\"|g" /etc/gw-tester/enb.yml
+    sed -i "s|  s1c_ip:.*|  s1c_ip: \"${s1c_ip}\"|g" /etc/gw-tester/enb.yml
 
-    for i in $(seq 2 254); do
+    s1u_ip=$(ifconfig $(ip a | grep {{ .Values.s1u.container_prefix | quote }} | awk -v FS="(: |@)" '{print $2; exit}') | awk '/inet addr/{print substr($2,6)}')
+    sed -i "s|  s1u_ip:.*|  s1u_ip: \"${s1u_ip}\"|g" /etc/gw-tester/enb.yml
+
+    euu_if=$(ip a | grep {{ .Values.euu.container_prefix | quote }} | awk -v FS="(: |@)" '{print $2; exit}')
+    sed -i '/subscribers:/,$d' /etc/gw-tester/enb.yml
+    echo "subscribers:" >> /etc/gw-tester/enb.yml
+    euu_ip=$(ifconfig $euu_if | awk '/inet addr/{print substr($2,6)}')
+    for i in $(seq 0 254); do
         if [ "10.0.3.$i" != "$euu_ip" ]; then
             format_num=$(printf "%03i" $i)
             cat <<EOL >> /etc/gw-tester/enb.yml
@@ -110,7 +118,7 @@ data:
         src_ip: "10.0.3.$i"
         i_tei: 0
         type: "external"
-        euu_if_name: "$euu_nic"
+        euu_if_name: "$euu_if"
         http_url: ""
         reattach_on_reload: false
     EOL
diff --git a/k8s/enb_nsm.yml b/k8s/enb_nsm.yml
--- a/k8s/enb_nsm.yml
+++ b/k8s/enb_nsm.yml
@@ -67,10 +67,15 @@ metadata:
   name: enb-init-script
 data:
   init.sh: |2
-    if [ $(curl http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip -s -o /dev/null -w "%{http_code}") == "200" ]; then
+    http_code=$(curl http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip -s -o /dev/null -w "%{http_code}")
+    if [ "$http_code" == "200" ]; then
         mme_s1c_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip | jq  -r ".node.value")
-    else
+    elif [ "$http_code" == "404" ]; then
         mme_s1c_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip?wait=true | jq  -r ".node.value")
+    else
+        echo "ERROR - eNB pod cannot reach the etcd service"
+        traceroute $LTE_ETCD_SERVICE_HOST -m 5 -p 12379 -q 1
+        exit 1
     fi
     sed -i "s|mme_addr:.*|mme_addr: \"${mme_s1c_ip}:36412\"|g" /etc/gw-tester/enb.yml
 
diff --git a/k8s/multus/charts/enb/templates/deployment.yaml b/k8s/multus/charts/enb/templates/deployment.yaml
--- a/k8s/multus/charts/enb/templates/deployment.yaml
+++ b/k8s/multus/charts/enb/templates/deployment.yaml
@@ -85,20 +85,35 @@ metadata:
   name: enb-init-script
 data:
   init.sh: |2
-    if [ $(curl http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip -s -o /dev/null -w "%{http_code}") == "200" ]; then
+    http_code=$(curl http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip -s -o /dev/null -w "%{http_code}")
+    if [ "$http_code" == "200" ]; then
         mme_s1c_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip | jq  -r ".node.value")
-    else
+    elif [ "$http_code" == "404" ]; then
         mme_s1c_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip?wait=true | jq  -r ".node.value")
+    else
+        echo "ERROR - eNB pod cannot reach the etcd service"
+        traceroute $LTE_ETCD_SERVICE_HOST -m 5 -p 12379 -q 1
+        exit 1
     fi
     sed -i "s|mme_addr:.*|mme_addr: \"${mme_s1c_ip}:36412\"|g" /etc/gw-tester/enb.yml
 
-    euu_ip=$(ifconfig {{ .Values.s1c.interface }} | awk '/inet addr/{print substr($2,6)}')
+    until ip add show {{ .Values.s1c.interface }} > /dev/null ; do
+        sleep 2
+    done
     s1c_ip=$(ifconfig {{ .Values.s1c.interface }} | awk '/inet addr/{print substr($2,6)}')
-    sed -i "s|s1c_ip:.*|s1c_ip: \"${s1c_ip}\"|g" /etc/gw-tester/enb.yml
-    s1u_ip=$(ifconfig {{ .Values.s1u.interface }} | awk '/inet addr/{print substr($2,6)}')
-    sed -i "s|s1u_ip:.*|s1u_ip: \"${s1u_ip}\"|g" /etc/gw-tester/enb.yml
+    sed -i "s|  s1c_ip:.*|  s1c_ip: \"${s1c_ip}\"|g" /etc/gw-tester/enb.yml
 
-    for i in $(seq 2 254); do
+    until ip add show {{ .Values.s1u.interface }} > /dev/null ; do
+        sleep 2
+    done
+    s1u_ip=$(ifconfig {{ .Values.s1u.interface }} | awk '/inet addr/{print substr($2,6)}')
+    sed -i "s|  s1u_ip:.*|  s1u_ip: \"${s1u_ip}\"|g" /etc/gw-tester/enb.yml
+
+    euu_if="{{ .Values.euu.interface }}"
+    sed -i '/subscribers:/,$d' /etc/gw-tester/enb.yml
+    echo "subscribers:" >> /etc/gw-tester/enb.yml
+    euu_ip=$(ifconfig $euu_if | awk '/inet addr/{print substr($2,6)}')
+    for i in $(seq 0 254); do
         if [ "10.0.3.$i" != "$euu_ip" ]; then
             format_num=$(printf "%03i" $i)
             cat <<EOL >> /etc/gw-tester/enb.yml
@@ -108,7 +123,7 @@ data:
         src_ip: "10.0.3.$i"
         i_tei: 0
         type: "external"
-        euu_if_name: "{{ .Values.euu.interface }}"
+        euu_if_name: "$euu_if"
         http_url: ""
         reattach_on_reload: false
     EOL
diff --git a/k8s/multus/charts/mme/templates/deployment.yaml b/k8s/multus/charts/mme/templates/deployment.yaml
--- a/k8s/multus/charts/mme/templates/deployment.yaml
+++ b/k8s/multus/charts/mme/templates/deployment.yaml
@@ -71,26 +71,37 @@ metadata:
   name: mme-init-script
 data:
   init.sh: |
-    if [ $(curl http://lte-etcd.default.svc.cluster.local:12379/v2/keys/pgw_s5c_ip -s -o /dev/null -w "%{http_code}") == "200" ]; then
+    http_code=$(curl http://lte-etcd.default.svc.cluster.local:12379/v2/keys/pgw_s5c_ip -s -o /dev/null -w "%{http_code}")
+    if [ "$http_code" == "200" ]; then
         pgw_s5c_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/pgw_s5c_ip | jq  -r ".node.value")
-    else
+    elif [ "$http_code" == "404" ]; then
         pgw_s5c_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/pgw_s5c_ip?wait=true | jq  -r ".node.value")
+    else
+        echo "ERROR - MME pod cannot reach the etcd service"
+        exit 1
     fi
     sed -i "s|pgw_s5c_ip:.*|pgw_s5c_ip: \"$pgw_s5c_ip\"|g" /etc/gw-tester/mme.yml
 
-    if [ $(curl http://lte-etcd.default.svc.cluster.local:12379/v2/keys/sgw_s11_ip -s -o /dev/null -w "%{http_code}") == "200" ]; then
+    http_code=$(curl http://lte-etcd.default.svc.cluster.local:12379/v2/keys/sgw_s11_ip -s -o /dev/null -w "%{http_code}")
+    if [ "$http_code" == "200" ]; then
         sgw_s11_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/sgw_s11_ip | jq  -r ".node.value")
-    else
+    elif [ "$http_code" == "404" ]; then
         sgw_s11_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/sgw_s11_ip?wait=true | jq  -r ".node.value")
+    else
+        echo "ERROR - MME pod cannot reach the etcd service"
+        exit 1
     fi
     sed -i "s|sgw_s11_ip:.*|sgw_s11_ip: \"$sgw_s11_ip\"|g" /etc/gw-tester/mme.yml
 
-    s11_ip=$(ifconfig {{ .Values.s11.interface }} | awk '/inet addr/{print substr($2,6)}')
+    until ip add show {{ .Values.s11.interface }} > /dev/null ; do
+        sleep 2
+    done
+    s11_ip=$(ifconfig s111 | awk '/inet addr/{print substr($2,6)}')
     sed -i "s|  s11_ip:.*|  s11_ip: \"${s11_ip}\"|g" /etc/gw-tester/mme.yml
 
     s1c_ip=$(ifconfig {{ .Values.s1c.interface }} | awk '/inet addr/{print substr($2,6)}')
-    curl -s "http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip" -XPUT -d value="$s1c_ip" > /dev/null
-    sed -i "s|s1c_addr:.*|s1c_addr: \"${s1c_ip}:36412\"|g" /etc/gw-tester/mme.yml
+    curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip -XPUT -d value="$s1c_ip" > /dev/null
+    sed -i "s|  s1c_addr:.*|  s1c_addr: \"${s1c_ip}:36412\"|g" /etc/gw-tester/mme.yml
 
     ip a
     ip route
